### ISSUE TITLE
2. Store interests in Model.java 

### ISSUE THREAD

**Issue by nvaa36** [lysanderp41/CodeUSummer2017#19]
Please finish issue #18 first.
Add 2 new fields under the Stores of users, conversations, and messages in Model.java: a set of all of the Interests objects for all the different users and a map that maps between the UUID of the Interests object and the UUID of the associated user object.

**Comment by mlk209** [comment]
Stores all the conversations/users that the user is interested in and maps the the UUID that contains the set of UUID's of the interested to the user.

**Comment by nvaa36** [comment]
Update: Only add the store into Model.java and just allow things to be found by user's UUID so the map is unnecessary.
