### ISSUE TITLE
Names with spaces are not supported

### ISSUE THREAD

**Issue by joecarnahan** [lysanderp41/CodeUSummer2017#45]
If I add a user or conversation whose name has spaces in it, then the transaction log gets lines like

`ADD-USER 15.3779943741 A A 1498621887072`
`ADD-CONVERSATION 15.3227467769 15.3162558029 B B 1498622147421`

Then, the server fails on startup because it tries to parse the part of the name after the space as a number.

**Comment by joecarnahan** [comment]
I've assigned this to Isaac after assigning the other persistence issue to Lysander.

You are welcome to trade, but I wanted each issue to be assigned to exactly one person so that we don't get any "I thought you were going to do it" problems.

**Comment by joecarnahan** [comment]
Suggestion was to change it to always quote names when they are written, so the transaction log would become

`ADD-USER 15.3779943741 "A A" 1498621887072`

Note that there's no harm in quoting names that *don't* have spaces.

**Comment by iZake** [comment]
I fix the program to write names in quotes to the transaction log.

**Comment by joecarnahan** [comment]
Cool! Do you have a pull request that we can merge into the medium feature branch?
